# Generated by Django 4.1.4 on 2024-01-06 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_details_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
